### ISSUE TITLE
Add `AVA` rule

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/clinton#11]
Check if AVA is installed and used in the test script. It would be nice to if we could specify the minimum version installed or `*` if you want the version to be specified as unicorn.

Any other suggestions?

// @sindresorhus

**Comment by sindresorhus** [comment]
👍 Would also be nice to have a check that ensures people are specifying AVA config in package.json instead of CLI arguments.

**Comment by SamVerschueren** [comment]
Thanks for the suggestion!

**Comment by SamVerschueren** [comment]
@sindresorhus Implemented the rule. If you have some time to check it out: [ava.js](https://github.com/SamVerschueren/clinton/blob/master/rules/ava.js).

**Comment by sindresorhus** [comment]
Looks good :)
