### ISSUE TITLE
Merge cli options with config file options?

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/clinton#14]
Currently, the rules provided via the `cli` and the rules provided via a config file are merged where the cli options have higher priority. Should we do that or should we implement that if cli options are provided, the config file options are dropped?

**Comment by sindresorhus** [comment]
Merge. That's how I do it in AVA and XO. The benefit is that it let's you define a base config in package.json and then override with CLI flags. You should recommend people use the config whenever possible for maintainability and to make it easier for eventual other tools to read the config.
