### ISSUE TITLE
Add `cli` rule

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/clinton#15]
A rule that checks if the package is a `cli` package (if `bin` is provided in `package.json`) and performs the following checks.

- Checks if the file exists
- Checks if the file is [executable](https://github.com/kevva/executable)
- Checks if [update-notifier](https://github.com/yeoman/update-notifier) is a dependency

Not sure about the `update-notifier` dependency though. Do we always want this?

// @sindresorhus

**Comment by sindresorhus** [comment]
> Not sure about the update-notifier dependency though. Do we always want this?

No, not always.

**Comment by SamVerschueren** [comment]
Alright, will drop that check then, thanks for the feedback!
