### ISSUE TITLE
Enforce all filenames to be lowercase

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/clinton#17]
Check if all the files are named lowercase. 

@sindresorhus @jamestalmage didn't you wrote this rule for XO? Couldn't find it.

**Comment by jamestalmage** [comment]
https://github.com/sindresorhus/eslint-plugin-xo/blob/master/docs/rules/filename-case.md

Code: https://github.com/sindresorhus/eslint-plugin-xo/blob/master/rules/filename-case.js

**Comment by SamVerschueren** [comment]
How could I have missed that :p. Thanks!
