### ISSUE TITLE
Enforce order of properties in package.json

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/clinton#2]
From @sindresorhus

> I would like to also see a property to enforce order of properties in package.json.

> A --fix option for that would be amazing.

**Comment by SamVerschueren** [comment]
@sindresorhus Implemented the `pkg-property-order` rule. This is the [default order](https://github.com/SamVerschueren/clinton/blob/master/rules/pkg-property-order.js#L2-L17). You can always pass in a custom order list when defining the rule.

```json
"clinton": {
    "pkg-property-order": ["error", "name", "description", "version"]
}
```

1. name
2. version
3. description
4. license
5. repository
6. author
7. main
8. bin
9. engines
10. scripts
11. files
12. keywords
13. dependencies
14. devDependencies

Anything missing or incorrect?

Only the properties that are listed in the order list will be checked. So you can add `xo` or `ava` somewhere in between if you want that. Or do you rather prefer a strict check and all the properties not listed in the order list should be placed at the bottom (below `devDependencies`)?

**Comment by sindresorhus** [comment]
You're missing a lot of properties, see all here: https://docs.npmjs.com/files/package.json (Leave out `engineStrict`, `directories`, as the former is deprecated and the latter not used).

Anything not defined in the above link should be enforced to the bottom.

**Comment by SamVerschueren** [comment]
Use the same order as specified on npmjs?

**Comment by sindresorhus** [comment]
Create a list of all of them here and I'll suggest a good order.

**Comment by SamVerschueren** [comment]
This should be the list. Thanks for helping out on this!

1. name
2. version
3. description
4. repository
5. author
6. homepage
7. bugs
8. private
9. config
10. publishConfig
11. license
12. main
13. bin
14. man
15. engines
16. os
17. cpu
18. scripts
19. preferGlobal
20. files
21. keywords
22. dependencies
23. devDependencies
24. peerDependencies
25. bundledDependencies
26. optionalDependencies

**Comment by sindresorhus** [comment]
```
name
version
description
license
repository
homepage
bugs
author
maintainers
private
preferGlobal
publishConfig
config
main
bin
man
os
cpu
engines
scripts
files
keywords
dependencies
devDependencies
peerDependencies
bundledDependencies
optionalDependencies
```

You forgot `maintainers`. I added it.

**Comment by SamVerschueren** [comment]
Thanks for the help @sindresorhus! 🎉

**Comment by SamVerschueren** [comment]
@sindresorhus I noticed that `contributors` isn't in the list either. Should we add it directly after `maintainers`?

```
name
version
description
license
repository
homepage
bugs
author
maintainers
private
preferGlobal
publishConfig
config
main
bin
man
os
cpu
engines
scripts
files
keywords
dependencies
devDependencies
peerDependencies
bundledDependencies
optionalDependencies
```

**Comment by sindresorhus** [comment]
Yes
