### ISSUE TITLE
Detect minimal node engine

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/clinton#20]
I'm not sure if this is something for `XO` or for `clinton`. Let me create it over here, we can still move the idea over.

I noticed this issue today: https://github.com/sindresorhus/username/issues/7

I was thinking that it would be nice if our linter failed on something like that. For instance, if `const`, `let` or fat-arrow functions are being used, the minimal engine should be set to `>=4`.

#### XO Vs. clinton

Clinton lints (or at least tries to) your project style. It does not do AST parsing or whatsoever. So the only way I can detect something like that is by just running regexes over the JavaScript file and search for strings like `const`, `let`, `=> {`, etc. So in that point of view, it might be better to do this with an ESLint plugin.

On the other side, ESLint lints your code. Would it make sense if it did something like this?

#### External package

It might be nice if we could create an external package, not tied to ESLint or clinton or whatsoever that detects the minimal node version of a file. If `const`, `let` and fat-arrow functions are being used, it should be 4.x at least. If default arguments are used, it should be `>=6`. Or if only `Promise` is used but not defined with something like `pinkie-promise`, it should be `>=0.12`.

Just something I'd like to discuss with you guys :).

// @sindresorhus @kevva @jamestalmage @jfmengels

**Comment by jfmengels** [comment]
There is an Eslint plugin rule that does that. https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-unsupported-features.md
Then again, the node version in the rule configuration and the specified node engine might be different.

**Comment by jfmengels** [comment]
The tricky bit when using it with AVA is that you use advanced JS syntax in parts of your code, which may get reported.

**Comment by SamVerschueren** [comment]
It could be added as a warning maybe?

**Comment by jfmengels** [comment]
You'd get hundreds of warning reports, so that's a no go IMO.

Maybe it could be added in XO with glob configurations (until the time glob config gets added to ESLint https://github.com/eslint/eslint/issues/3611) by disabling it only in the tests files.

**Comment by SamVerschueren** [comment]
Going to close this one as it will be very hard to do it right.
