### ISSUE TITLE
EditorConfig validator

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/clinton#24]
Validate the project settings via the `.editorconfig` file.

**Comment by sindresorhus** [comment]
What exactly would it validate?

**Comment by SamVerschueren** [comment]
I was thinking of validating if the project uses `tabs` and `spaces` for `package.json` and `*.yml` files. It should be configurable though via arguments. Or do you think it's overkill to test something like this?

**Comment by sindresorhus** [comment]
I think it could be useful. Maybe also test if there are files in the project that doesn't match any of the patterns in .editorconfig.

**Comment by SamVerschueren** [comment]
Very nice idea! Could be really helpful.
