### ISSUE TITLE
Add `ignores` property

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/clinton#29]
Just like `XO` https://github.com/sindresorhus/xo#ignores

**Comment by GitScrum** [comment]
@SamVerschueren npm publish ?

**Comment by SamVerschueren** [comment]
Have to disable the editorconfig linter first because it can't detect smartabs which causes me to disable the entire rule on almost every project. Will try to release it tomorrow.

**Comment by SamVerschueren** [comment]
`0.6.0` released

**Comment by GitScrum** [comment]
thanks
