### ISSUE TITLE
node_modules is not in kebab case

### ISSUE THREAD

**Issue by GitScrum** [SamVerschueren/clinton#32]
[see my test](https://travis-ci.org/GitScrum/post-sequence/jobs/148976754)

**Comment by SamVerschueren** [comment]
Wow, that's odd. All the files/directories in `.gitignore` should be ignored by clinton. Let me clone your repo and try it locally.

**Comment by SamVerschueren** [comment]
It seems to work locally. Does it work locally for you?

**Comment by GitScrum** [comment]
no, i cloned my repo `post-sequence`, ` run npm i && npm t` - test has passed, after i run ` npm rm -D clinton && npm i -D` will installed clinton v.0.7.1 - test has broken and report me:
```bash
> post-sequence@0.1.3 pretest D:\sand-box\git\post-sequence
> clinton && npm run lintjs && npm run lintmd

  D:\sand-box\git\post-sequence\.nyc_output
    × Filename is not in kebab case. Rename it to `.nyc-output`. (filename-case)

  D:\sand-box\git\post-sequence\CHANGELOG.md
    × Filename is not in kebab case. Rename it to `changelog.md`. (filename-case)

  D:\sand-box\git\post-sequence\LICENSE
    × Filename is not in kebab case. Rename it to `license`. (filename-case)

  D:\sand-box\git\post-sequence\node_modules
    × Filename is not in kebab case. Rename it to `node-modules`. (filename-case)

npm ERR! Test failed.  See above for more details.
```

**Comment by SamVerschueren** [comment]
What's the output of `cat .gitignore`?

**Comment by GitScrum** [comment]
I understand what the problem is )) node_modules != node_module/

**Comment by GitScrum** [comment]
```
node_modules/  
.nyc_output/  
npm-debug.log  
lib/  
_gh-pages/  
.publish/  
*.sublime*  
coverage/  
tmp/  
```

**Comment by SamVerschueren** [comment]
Oh you're right. Because it uses globbing patterns, it uses `node_modules/` to ignore the files inside `node_modules` but not the directory itself. So how should I solve this? I believe adding `node_modules/` to `.gitignore` might be wrong. It ignores the contents inside the `node_modules` directory but not the directory itself. Because the directory is empty, it will not be pushed upstream. Not sure though.

@sindresorhus care to chime in?

**Comment by GitScrum** [comment]
> I believe adding node_modules/ to .gitignore might be wrong.

you right, maybe lint this or throw recommendation/warning ?

**Comment by SamVerschueren** [comment]
> you right, maybe lint this or throw recommendation/warning ?

Good point, let me create an issue for this. Can we close this then?

**Comment by GitScrum** [comment]
yep, thanks for you pkg 👍

**Comment by SamVerschueren** [comment]
You're welcome, happy to see some people starting to use it. It helps me to iron out some bugs and improve it. So if you have any ideas for other rules, or improvements whatsoever, do not hesitate to open a new issue!
