### ISSUE TITLE
Add `.DS_Store` to ignores list by default

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/clinton#33]
To prevent errors like

>   /Users/sam/Projects/foo/.DS_Store
>     ✖ Filename is not in kebab case. Rename it to `.ds-store`. (filename-case)

**Comment by sindresorhus** [comment]
Was just going to report this. You could use my [`junk`](https://github.com/sindresorhus/junk) module to filter it out.

**Comment by sindresorhus** [comment]
Clinton should also include `node_modules`:

```
/Users/sindresorhus/dev/ava/test/fixture/watcher/tap-in-conf/node_modules
    ✖ Filename is not in kebab case. Rename it to `node-modules`. (filename-case)
```

And files prefixed with underscore:

```
/Users/sindresorhus/dev/ava/test/fixture/_generate_source-map-initial.js
    ✖ Filename is not in kebab case. Rename it to `_generate-source-map-initial.js`. (filename-case)
```

And these:

```
  /Users/sindresorhus/dev/ava/.github/issue_template.md
    ✖ Filename is not in kebab case. Rename it to `issue-template.md`. (filename-case)

  /Users/sindresorhus/dev/ava/.github/pull_request_template.md
    ✖ Filename is not in kebab case. Rename it to `pull-request-template.md`. (filename-case)
```

**Comment by SamVerschueren** [comment]
> Clinton should also include `node_modules`

Currently everything from `.gitignore` should be excluded. See #32. Have to check why that one is still added though because `ava` is clearly ignoring `node_modules`. But might be best practice to just ignore them hardcoded.

> And files prefixed with underscore

Is that the convention for generated files? Prefix them with `_`?

> And these

You mean ALL `.md` files?

**Comment by sindresorhus** [comment]
> But might be best practice to just ignore them hardcoded.

In this case yes. Some people commit their node_modules, and still wouldn't want it linted.

> Is that the convention for generated files? Prefix them with _?

No, but it's a convention in many ecosystem, so shouldn't be forced to kebab case. We use it in AVA for helper files and Sass uses it for includes.

> You mean ALL .md files?

No, just everything in a `.github` folder in root. Actually, I would just ignore all dotfiles.

**Comment by SamVerschueren** [comment]
Ok thanks for all the information and feedback. Will work on it. Much appreciated :)!

**Comment by SamVerschueren** [comment]
I'm not going to disable all the dotfiles/folders by default. I'm linting `.travis.yml` for instance and might be linting other dotfiles in the future as well. So I will exclude `.github` for now and others can still be added later on if they appear to be annoying.

**Comment by sindresorhus** [comment]
> I'm not going to disable all the dotfiles/folders by default. I'm linting .travis.yml for instance and might be linting other dotfiles in the future as well. So I will exclude .github for now and others can still be added later on if they appear to be annoying.

Obviously. I meant that it might be easier to whitelist the dotfiles you want than having to continuously blacklist new dotfiles people encounter.

**Comment by SamVerschueren** [comment]
Whitelisting might be better and less annoying for the future indeed.
