### ISSUE TITLE
Lint `gitignore`

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/clinton#34]
Some people tend to ignore `node_modules/` instead of `node_modules`. These are different things because `node_modules/` ignores the contents of the directory but not the directory itself. Because the directory is empty (after ignoring the content), the directory isn't pushed upstream so they might look identical but they are not.

**Comment by SamVerschueren** [comment]
Also check if a `.gitignore` is present AND that `node_modules` is being ignored.

**Comment by sindresorhus** [comment]
:+1:

**Comment by SamVerschueren** [comment]
I've added this rule which checks for the presence of `.gitignore`. It also checks if `node_modules` is being ignored. 

But I'm not checking what I initially had in mind. Is it important to check for `node_modules` Vs. `node_modules/`? I created this issue because I came across `node_modules` Vs. `node_modules/` but I can't recall the context anymore. So double checking first before I drop the idea.
