### ISSUE TITLE
Use relative paths in the output

### ISSUE THREAD

**Issue by sindresorhus** [SamVerschueren/clinton#35]
Before:

```
/Users/sindresorhus/dev/ava/test/fixture/.DS_Store
    ✖ Filename is not in kebab case. Rename it to `.ds-store`. (filename-case)
```

After:

```
test/fixture/.DS_Store
    ✖ Filename is not in kebab case. Rename it to `.ds-store`. (filename-case)
```

**Comment by SamVerschueren** [comment]
Not sure about the implementation though. I calculate the relative paths in `cli.js` but internally the `file` property is still absolute. Is this ok, or should I handle it internally and let don't bother `cli.js` with this?

Feedback, remarks or just radiosilence. Everything is welcome :).

**Comment by sindresorhus** [comment]
cli.js is the correct place
