### ISSUE TITLE
Reports about non-existing file

### ISSUE THREAD

**Issue by sindresorhus** [SamVerschueren/clinton#36]
```
~/dev/acosh master
❯ clinton
  /Users/sindresorhus/dev/acosh/.__browserify_string_empty.js
    ✖ Filename is not in kebab case. Rename it to `.browserify-string-empty.js`. (filename-case)
```

I've seen this on multiple repos.

**Comment by SamVerschueren** [comment]
And you are 100% sure that the file does not exist? Cloned the repo and ran `clinton` but the only error it shows is

```
  /Users/sam/Projects/opensource/forks/acosh/package.json
    ✖ XO is not installed as devDependency. (xo)
```

**Comment by sindresorhus** [comment]
I thought I was, but it shows up in the CLI:

```
~/dev/acosh master
❯ tree -a
.
├── .DS_Store
├── .__browserify_string_empty.js
├── .editorconfig
```

But not in Finder. Wuuut.

**Comment by sindresorhus** [comment]
Seems like files starting with `.__` are hidden even when hidden files are turned on in Finder.

**Comment by SamVerschueren** [comment]
Too bad we don't have an option to show hidden hidden files then :p. That's really odd, never came across something like that.

Safe to close this one then?

**Comment by sindresorhus** [comment]
Yes
