### ISSUE TITLE
Enforce order of fields in "author" in package.json

### ISSUE THREAD

**Issue by sindresorhus** [SamVerschueren/clinton#39]
This order: https://github.com/sindresorhus/np/blob/9ea8f5aa9f05ef6e2c236977141eb8b2bc693e5d/package.json#L8-L10 `name`, `email`, `url`.

**Comment by SamVerschueren** [comment]
Same goes for `maintainers` if a maintainers list is found?

**Comment by sindresorhus** [comment]
Yup, and `contributors`.

**Comment by SamVerschueren** [comment]
Any improvements on the error message? Tried a couple of things but this was the best I could come up with.

![screen shot 2016-08-05 at 16 36 12](https://cloud.githubusercontent.com/assets/1913805/17439964/c17a0b0a-5b2a-11e6-8977-8da22685d8cf.png)

**Comment by sindresorhus** [comment]
Looks great
