### ISSUE TITLE
Ensure shorthand "repository" in package.json when GitHub repo

### ISSUE THREAD

**Issue by sindresorhus** [SamVerschueren/clinton#40]
`sindresorhus/np` and not the following:

- `https://github.com/sindresorhus/np.git`
- `https://github.com/sindresorhus/np`
- `{"type": "git", "url": "https://github.com/sindresorhus/np.git"}`
- `{"type": "git", "url": "https://github.com/sindresorhus/np"}`

**Comment by SamVerschueren** [comment]
This only applies when it's GitHub right? If it's BitBucket, it should be the full url?

**Comment by sindresorhus** [comment]
Yes
