### ISSUE TITLE
Undefined line:column in some projects

### ISSUE THREAD

**Issue by sindresorhus** [SamVerschueren/clinton#47]
```
ansi-regex

  package.json:undefined:undefined
  ✖  Specify AVA config in package.json instead of passing it through via the CLI.  ava

  1  error
```

```
anybar

  package.json:undefined:undefined
  ✖  Property dependencies should occur before property devDependencies.  pkg-property-order

  1  error
```

**Comment by SamVerschueren** [comment]
Will look into it tomorrow.

**Comment by SamVerschueren** [comment]
Oh ok, this is added by `eslint-formatter-pretty`. Why are these actually added and made invisible?

**Comment by sindresorhus** [comment]
Oh, right. It's so you can just click the title in iTerm (and other terminals supporting that) and have it open in your editor on the correct line. You need to add a conditional there too about the missing line:column.

**Comment by SamVerschueren** [comment]
Wow, very nice feature :). Will do a PR this evening.

**Comment by SamVerschueren** [comment]
Should be fixed after reinstalling because of `eslint-formatter-pretty@0.3.1`
