### ISSUE TITLE
Bump code coverage to 95+

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/clinton#53]
Currently the code coverage is pretty low (`79%`). I'd like to have it at least `90%`, if possible even higher. The major problem is that currently the `fix` methods aren't being tested. How should we test them? I believe the best thing we can do is to copy over the files to a temporary directory and fix them over there. Might be hard to set up though so have to investigate first.

**Comment by sindresorhus** [comment]
> How should we test them?

Return the original content and the fixed content of a file in the API.

**Comment by SamVerschueren** [comment]
Thanks for the feedback. Will look into that option.

**Comment by SamVerschueren** [comment]
With f9ad52c156ad9fb0ecb1cda524400eeac04cbd18 came the possibility to test fixers. We've now reached a code coverage of 92%.

I still think we have some low hanging fruit to increase this even more.
