### ISSUE TITLE
Check files for merge conflicts

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/clinton#55]
Merge conflicts appear in a file like this

```
<<<<<<< HEAD
foo
=======
bar
>>>>>>> development
```

Questions I have for implementing this
1. Would it be enough to only check for the `<<<<<<<` sequence, or should we really check the entire block with the `========` sequence and `>>>>>>>>>` as well?
2. Is the first block always named `HEAD` or could it be something else as well?

// @jfmengels @sindresorhus

**Comment by jfmengels** [comment]
1. I would check for each separately. If I resolved a merge conflict partially and forgot to remove the zjomeqifoiqjzefjiomqzeofijqzoeifj
```
bar
>>>>>>> development
```

2. The first block can be named something else, so you should not check that.

**Comment by SamVerschueren** [comment]
Thanks for the feedback!
