### ISSUE TITLE
plugin in rules ?

### ISSUE THREAD

**Issue by GitScrum** [SamVerschueren/clinton#57]
Why plugins are the rules ? In poorer time, I see a trend `{ ...options, plugins: {...}, extends: {}, preset: {...}, rules: {...}}`

**Comment by SamVerschueren** [comment]
Can you elaborate? Don't think I follow entirely :).

**Comment by GitScrum** [comment]
Example in readme:
```json
"clinton": { "rules": { "file-exists": ["error", "index.js"] } }
```

Why not ?
```json
"clinton": { "plugins": { "file-exists": ["error", "index.js"] } }
```

**Comment by GitScrum** [comment]
And I'd do the `plugins` array

**Comment by SamVerschueren** [comment]
Oh you're right, the `readme` is incorrect. It should be `plugins` instead of `rules`.
