### ISSUE TITLE
Remove `esnext` recommendation from XO rule

### ISSUE THREAD

**Issue by sindresorhus** [SamVerschueren/clinton#62]
> Enforce ES2015+ rules with the esnext option.

It's going to be `true` by default in the next XO version: https://github.com/sindresorhus/xo/commit/61c046cab3d908c4c0582211d215e4c7f0d7cf20

**Comment by SamVerschueren** [comment]
Maybe we should reverse it then. If `node <=0.12` is still supported, set it to `false`.

But maybe that doesn't make sense. The latest `XO` doesn't support those anymore right? So the latest `XO` wouldn't run on those versions...

**Comment by sindresorhus** [comment]
Yup, doesn't make sense. Latest XO requires Node.js 4.
