### ISSUE TITLE
Question: What's the origin of the `package.json` property order?

### ISSUE THREAD

**Issue by alebelcor** [SamVerschueren/clinton#70]
Hi,

I'm wondering where the property order of the [`pkg-property-order` rule](https://github.com/SamVerschueren/clinton/blob/master/rules/pkg-property-order.js) comes from. 

It seems a bit different than the order in the [npm documentation](https://docs.npmjs.com/files/package.json).

Awesome project! Thanks!

**Comment by SamVerschueren** [comment]
Hi, first of all, thanks for using it. If you have any improvements or ideas for new rules, don't hesitate to create new issues for them. 

The order is based on own usage from me and @sindresorhus. So it's not based upon the npmjs docs. This is the order we use on our projects for consistency.

**Comment by sindresorhus** [comment]
The order in the npm docs is just arbitrary. The order here is something I've iterated on through many years. It's basically: package info, authors, package config, dependencies.
