### ISSUE TITLE
Unable to create a plugin

### ISSUE THREAD

**Issue by brekk** [SamVerschueren/clinton#85]
Hi there,

I love the idea for this library, thank you for creating it.

I was following the basic outline of [the example](https://github.com/SamVerschueren/clinton#example), but as I was attempting to write tests for my plugin module, I noticed that the internal definition for plugins: https://github.com/SamVerschueren/clinton/blob/master/lib/utils/rule.js#L7 defaults to an array, and the following line uses `.indexOf` to test for plugin matching. Relative to the example providing:

```json
{
		"plugins": {
			"file-exists": ["error", "index.js"]
		}
}
```

How is one supposed to supply plugins to the config? If it's as an object, then I am concerned that the existing test (`plugins.indexOf(ruleId)`) will never match anything. If it's as an array, then I don't know how to pass configuration to it, and the example code is mismatched.

Could you provide a simple standalone example of how to create a plugin with tests?

If needed I can publish my example code.

**Comment by SamVerschueren** [comment]
You are right, I believe the docs are wrong. I'll look into it and get back to you.

**Comment by brekk** [comment]
Any update on this?

**Comment by SamVerschueren** [comment]
Sorry for the late reply and thanks for pinging me back, lost this one out of sight. 
The `package.json` example should be like this.

```json
{
	"name": "Unicorn",
	"description": "My unicorn package",
	"version": "1.0.0",
	"scripts": {
		"test": "clinton"
	},
	"devDependencies": {
		"clinton": "*",
		"clinton-plugin-file-exists": "1.0.0"
	},
	"clinton": {
		"plugins": [
			"file-exists"
		],
		"rules": {
			"file-exists": ["error", "index.js"]
		}
	}
}
```

So yes, the `plugins` list is an array and just defines the additional plugins. And then you have to enable them in the `rules` object and you can pass in some parameters.
