### ISSUE TITLE
Opinionated ideas

### ISSUE THREAD

**Issue by dy** [SamVerschueren/clinton#88]
@SamVerschueren do you mind if I put some ideas to make clinton a single project linting tool? Please feel free to take them over or delete the issue.

* Make sure package has `build` script on prepublish, optionally compiling code to ES5/ES3, shaking tree, converting import/export to CJS, babel etc. (to avoid publishing unbuilt source)
* Make sure regular linter (eslint or alike) and tests pass
* Make sure readme has all necessary sections: description, [logo/image], usage, badges, API, license etc. Would be nice to give recommendations instead of warnings.
* Make sure `.npmignore` or `files` in `package.json` has redundant directories and files, like images, docs, etc.
* Make sure `.gitattributes` includes proper linguist config eg. https://github.com/a-vis/regl-line2d/blob/master/.gitattributes
* Make sure project has demo page (optional)

**Comment by sindresorhus** [comment]
> Make sure package has build script on prepublish, compiling code to ES5 or ES3 (to avoid publishing unbuilt source)

👎 ES2015 all the way. No need to compile down unless you use non-standard syntax.

> Make sure .npmignore has redundant directories and files, like images, docs, etc.

This should be ensuring you specify a `files` field in package.json instead.

> Make sure .gitattributes includes proper linguist config eg. a-vis/regl-line2d:.gitattributes@master

That is only needed the few times GitHub doesn't correctly detect it. In most cases it will.

**Comment by BE-Qdata** [comment]
#BE~~<Qdata>

**Comment by dy** [comment]
Not sure why I even started giving unsolicited advice.
